# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

all:

  # Upload limit (in gigabytes), possible values:
  #  Zero              => Uploads forbidden
  #  Negative integer  => Unlimited uploads
  #  Positive integer  => Number of gigabytes
  upload_limit: -1

  # Use sfMemcacheCache if you want a distributed cache.
  # sfAPCCache can do the trick for a single instance (sfAPCuCache in PHP 5.5).
  cache_engine: sfAPCCache

  # Enable read only mode
  read_only: false

  # LDAP authentication
  # TODO: These are some defaults for MoMA that SHOULD NOT be in this repository
  ldap_account_suffix: @museum.moma.org
  ldap_base_dn: DC=MUSEUM,DC=MOMA,DC=ORG
  ldap_domain_controllers: momadc01.museum.moma.org # comma-separated list
  ldap_user_group: CN=DRMC MA,OU=DRMC,OU=Service Accounts,DC=MUSEUM,DC=MOMA,DC=ORG

  # Used in the repo template
  # google_maps_api_key: ...

  # Google Analitycs
  # google_analytics_api_key: ...
