indexSuccess:
  javascripts:
    blank:

advancedSuccess:
  stylesheets:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/ui/ui.all.css:
  javascripts:
    /js/advancedSearch.js:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/jquery.once.js:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/ui/ui.datepicker.js:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/collapse:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/form:
    /vendor/yui/animation/animation-min:
    /vendor/yui/connection/connection-min:
    /vendor/yui/datasource/datasource-min:
    /vendor/yui/autocomplete/autocomplete-min:
    /vendor/yui/container/container-min:
    autocomplete:
    multiRow:

globalReplaceSuccess:
  stylesheets:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/jquery.once.js:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/collapse:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/form:
    multiRow:

descriptionUpdatesSuccess:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/tableheader:

